apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: project-info-manager-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: project-info-manager-traefik-app
    k8s.kuboard.cn/workload: project-info-manager-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-project-info-manager-prefix@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/project-info-manager/version
            backend:
              serviceName: project-info-manager
              servicePort: 50310
          - path: /api/project-info-manager/v1/get/coin
            backend:
              serviceName: project-info-manager
              servicePort: 50310
          
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.ohhash-production.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.jh-development.npool.top
      http: *http_rules
    - host: api.singapore-testing.npool.top
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: project-info-manager-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: project-info-manager-traefik-app-user
    k8s.kuboard.cn/workload: project-info-manager-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-strip-project-info-manager-prefix@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/project-info-manager/v1/create/coin
            backend:
              serviceName: project-info-manager
              servicePort: 50310
          - path: /api/project-info-manager/v1/create/app/coin
            backend:
              serviceName: project-info-manager
              servicePort: 50310
          - path: /api/project-info-manager/v1/update/coin
            backend:
              serviceName: project-info-manager
              servicePort: 50310
          - path: /api/project-info-manager/v1/get/app/coin
            backend:
              serviceName: project-info-manager
              servicePort: 50310
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
    - host: api.ohhash-production.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.jh-development.npool.top
      http: *http_rules
    - host: api.singapore-testing.npool.top
      http: *http_rules
